name: Black Code Formatter Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Black Code Formatter Check
        uses: psf/black@stable
        with:
          args: ". --diff --check"
